module SerializationTests

open System
open Xunit
open PiCamCommon

[<Fact>]
let ``PiCam client can deserialize JSON generated by Azure Function`` (): unit =
    let none = { NextPictureIn = None }
    let some = { NextPictureIn = Some(TimeSpan.FromMinutes 15.) }
    
    let noneJson = NextPictureModel.serialize none
    let someJson = NextPictureModel.serialize some

    let noneDeserializedRecord = NextPictureModel.deserialize noneJson
    let someDeserializedRecord = NextPictureModel.deserialize someJson

    Assert.Equal(none, noneDeserializedRecord)
    Assert.Equal(some, someDeserializedRecord)
