module SerializationTests

open System
open Xunit
open PiCamCommon

[<Fact>]
[<Trait("TestType", "Unit")>]
let ``PiCam client can deserialize JSON generated by Azure Function`` (): unit =
    let none = ExitLoop
    let some = TakeNextPictureIn (TimeSpan.FromMinutes 15.) 
    
    let noneJson = NextOperation.serialize none
    let someJson = NextOperation.serialize some

    let noneDeserializedRecord = NextOperation.deserialize noneJson
    let someDeserializedRecord = NextOperation.deserialize someJson

    Assert.Equal(none, noneDeserializedRecord)
    Assert.Equal(some, someDeserializedRecord)
